language: ruby
cache: bundler

rvm:
  - 2.4.1

before_script: 
  - 'bundle update'
  - 'bundle install'
script: 'cucumber features/check_title_of_webpage.feature'

branches:
  only:
    - saos

notifications:
  email:
    - dhimas@mokapos.com
