os: osx

language: ruby
cache: bundler

rvm:
  - 2.4.1

before_install:
  - gem update --system
  - gem --version
install: gem install rails

before_script: 
  - 'bundle install'

branches:
  only:
    - saos

notifications:
  email:
    - dhimas@mokapos.com
